apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: face-swapper-storage
  namespace: face-swapper
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
